---
title: "Assignment 02"
subtitle: "C++ Object-oriented Programming"
author:
    Khiem Nguyen 
    <br> Lecturer in Multiscale Materials
    <br> <khiem.nguyen@glasgow.ac.uk>
author-meta: "Lecturer in Multiscale Materials"
jupyter: false
execute: 
  eval: true
format: 
    html:
        # page-layout: full
        margin-left: 0.5em
        margin-right: 0.5em
        css: style.css
        number-sections: true
        number-depth: 3
        toc: true               # table of content
        toc-location: left      # table of content on the left
        toc-title: "Table of Content"   # table of content title

    # pdf:
    #     geometry:
    #         - top=24px
    #         - bottom=24px
    #         - left=36px
    #         - right=36px
    #     css: style.css
    #     number-sections: true
    #     number-depth: 2
    #     colorlinks: true
---

# Deploying `LinearRegression` and `LogisticRegression`

Before we discuss the mathematics behind Linear Regression and Logistic Regression, let us examine two examples given in the two above-mentioned files `concrete.csv` and `ecg.csv`. We first write a Python program to make prediction of concrete strength and then another program to make prediction whether a patient is fine or not given their ECG data.

## Linear regression using `LinearRegression`

We shall study two applications of `LinearRegression`

- Predict the concrete strength using $8$ features of technical info of the concrete.
- Build a simple polynomial prediction model.

### Predict the strength of concrete
First, we need to load data using the library Pandas and then convert the data into `ndarray`.

```{python}
import pandas as pd
import numpy as np
df = pd.read_csv("./data/concrete.csv") # concrete_data is a DataFrame object
data = df.to_numpy()    # now, it is a ndarray object
print(f"First 5 rows of this concrete dataset:\n {df.head()}")
```

This is a pretty sizable dataset. Both input features $\mathbf{x}^{(i)}$ and output label $y^{(i)}$ are stored in one single variable `data`. The first $8$ columns correspond to the input $\mathbf{x}$ and the last column to the output $y$. We extract `X` and `y` from this variable `data`:

```{python}
X = data[:,:-1]     # all rows, all columns from the first to the second last
y = data[:,-1]      # all rows, last column
```

You will learn that we need to test whether our prediction model is good or not. However, all the data we have are only avaliable in the `csv` file. For this reason, machine learning practioners normally split the dataset into two sets: [**training set**]{style="color:brown"} and [**test set**]{style="color:brown"}. The training set is used to train the machine learning model, which means seeking the model parameters $\mathbf{w}$ and $b$ explained in Assignment 1. In our project, we don't have to training-test split when we build the library. I just want to explain the point.

```{python}
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score    # to evaluate how good the model is later

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)
```

Training the model by using class [`LinearRegression`](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html) from **scikit-learn** is ridiculously easy as all the power-lifting has been done by the library.

```{python}
model = LinearRegression()  # define a LinearRegression model
model.fit(X_train, y_train) # training happens here -- look for model parameters w, b
```

As explained above, we need to assess how good our prediction model is. To do this, we compute the [**coefficient of determination**], denoted $R^2$ and pronounced "R squared", on both the training set and the test set. We normally call this measurement $R^2$ scaore. The $R^2$ score is defined by

$$
R^2 = 1 - \frac{\sum\limits_{i=1}^{m}(y^{(i)} - \widehat{y}(\mathbf{x}^{(i)}))^2}{\sum\limits_{i=1}^{m}(y^{(i)} - \overline{y})^2} = 1 - \frac{S_{\text{residual}}}{S_{\text{total}}}
$$
As we can see, if our prediction model is very good, the nominator $S_{\text{residual}}$
will be pretty small because the predicted value $\widehat{y}(\mathbf{x}^{(i)})$ is very close to the actual label $y^{(i)}$, making the entire fraction $\frac{S_{\text{residual}}}{S_{\text{total}}}$ is pretty small and hence the $R^2$ is close to $1$. On the other hand, if our model makes bad predictions, the nominator $S_{\text{residual}}$ is rather large, making the entire fraction $\frac{S_{\text{residual}}}{S_{\text{total}}}$ is large too. In extreme cases where the prediction model is unreasonably bad, this fraction can be larger than $1$ and thus $R^2$ score can be negative.

**Summary**

The $R^2$ score being close to $1$ means the model predicts extremely well, the score being close to $0$ means the model predicts extremely bad. Note that $R^2$ score can be negative -- The square term may be misleading you to think that it must be a non-negative number.


```{python}
train_r2_score = r2_score(y_true=y_train, y_pred=model.predict(X_train))
test_r2_score = r2_score(y_true=y_test, y_pred=model.predict(X_test))
print(f"Training R^2 Score: {train_r2_score:.4f}")
print(f"    Test R^2 Score: {test_r2_score:.4f}")
```

According to these $R^2$-score, the model has done a pretty good job in predicting the concrete strength given $8$ input features.

### Build a polynomial regression model

In this example, we generate a dataset with one single feature by adding noise to data points created on the graph of a cubic function
$$
p(x) = x (x - 1)(x + 1) = x^3 - x
$$

```{python}
import numpy as np
import matplotlib.pyplot as plt
np.random.seed(42)
n_samples = 100
poly_true = lambda x: x * (x - 1) * (x + 1)
x_data = np.random.uniform(-1.5, 1.5, n_samples)
y_true = poly_true(x_data)
noise = np.random.normal(0, 0.2, size=n_samples) * y_true
y_data = y_true + noise
xx = np.linspace(-1.5, 1.5, 1000)

plt.figure(figsize=(4, 2.5))
plt.plot(xx, poly_true(xx))
plt.scatter(x_data, y_data, marker='x', c='k', s=6)
plt.grid(True)
```

As we can see, at this point we have the dataset
$$
\mathcal{D} = \Big\{(x^{(1)}, y^{(1)}), \ldots, (x^{(m)}, y^{(m)}) \Big\}
$$
with $x^{(i)} \in \mathbb{R}$. Apparently, if we try to fit a line to this dataset, the fitting line has no chance to really fit the data well. One cannot "fit" a straight line to a curve. To build a model that fits this kind of data, we apparently that the following function will do a pretty good job
$$
f_{\mathbf{w}, b}(\mathbf{x}) = w_1 x + w_2 x^2 + w_3 x^3 + b = \mathbf{w}\cdot \mathbf{x} + b,
$$ {#eq-cubic-regression-model}
where
$$
\mathbf{w} = (w_1, w_2, w_3), \quad \mathbf{x} = (x, x^2, x^3).
$$
You should see immediately from @eq-cubic-regression-model that "[Wait a minute](https://www.youtube.com/watch?v=cw9FIeHbdB8)", that's exactly a linear regression model with $3$ features, each feature $x_j$ is formed by taking the original feature $x$ to power $j$. That is, we have $x_1 = x^{1}, x_2 = x^{2}, x_{3} = x^3$.

It is very easy to form these features in NumPy. Fortunately, scikit-learn gives us a tool to do this too. In the following code, the feature $x^{0} = 1$ is also added to the matrix `X_poly`.

```{python}
from sklearn.preprocessing import PolynomialFeatures
poly_features = PolynomialFeatures(degree=3)
X_data = x_data.reshape((-1, 1))
X_poly = poly_features.fit_transform(X_data)
print(f"X_poly =\n{X_poly[:4]}") # print the first 4 samples
print(f"X_poly.shape = {X_poly.shape}")
```
Since we don't need the bias feature $x^{0}$, let us redo this step without this bias feature
```{python}
poly_features = PolynomialFeatures(degree=3, include_bias=False)
X_poly = poly_features.fit_transform(X_data)
print(f"X_poly =\n{X_poly[:4]}") # print the first 4 samples
print(f"X_poly.shape = {X_poly.shape}")
```

The synthetical dataset is ready. We can now proceed to build the linear regression as in the last application.
```{python}
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_poly, y_data)
```

If you think about this whole process "long enough", you will see that the linear regression model we have just built is nothing but just a function of multiple variable. That is, given a vector $\mathbf{x} = (x_1, x_2, x_3)$ this model gives me the value $\widehat{y} = f_\mathbf{w}, b(\mathbf{x})$. That's it. Therefore, to justify the prediction power of this model, let us try to visualize it. Hopefully, it should agree well with the original polynomial $p(x) = x(x-1)(x+1)$. However, as just explained, this model is a function of three variables. To visualize it, we must provide the input the inform $(x, x^{2}, x^{3})$. This is exactly what we will achieve in the following code.
```{python}
xx = np.linspace(-1.5, 1.5, 500)
XX = poly_features.fit_transform(xx.reshape(-1, 1))
plt.figure(figsize=(5, 3.5))
plt.plot(xx, poly_true(xx), 'k--', label="hidden manifold - true model")
plt.plot(xx, model.predict(XX), label='polynomial regression model')
plt.scatter(x_data, y_data, marker='x', s=6, c='r')
plt.legend()
plt.grid(True)
```

Here we go. The polynomial regression model closely fits the true (hidden) manifold that is used to generate the synthetic and random data.

## Logistic regression using `LogisticRegression`

We will study two applications of `LogisticRegression`

- Classify Electrocardiogram dataset into two classes: normal or abnormal
- Classify gray-scale hand-written images into $10$ classes: digits $0, 1, \ldots, 9$

### Electrocardiogram (ECG) anomaly detection

In this application, given an electrocardiogram of a patient we try to predict whether the patient is fine or not. This is a binary classification problem in which a data sample is classified as either $0$ or $1$, "yes" or "no". The following Python code snippet will walk you through how the [`LogisticRegression`](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html) from **scikit-learn** perform binary classification.

**Load the dataset**

As before, we need to load the csv file into an `ndarray` to prepare the data for training the logistic regression model. The dataset consists of $4997$ samples, each sample has $140$ input features and one single output label taking value either $0$ or $1$.

In our ECG example, the label values are interpreted according to
- label equal to $1$: **normal** -- the patient is fine
- label equal to $0$: **abnormal** -- the patient is **not fine**

```{python}
import pandas as pd
df = pd.read_csv("./data/ecg.csv")  # df is a dataframe
data = df.to_numpy()    # convert dataframe into numpy array
print(f"type(df) = {type(df)}")

X = data[:,:-1] # all the features in the first 140 columns
y = data[:,-1]  # label of data (y vlaue) in the last column
n_samples = X.shape[0]          # number of samples
n_features = X.shape[1]         # number of features
n_classes = len(np.unique(y))   # number of classes in the classification problem

# Number of labels equal to 0
print(f"number of labels = 0: {np.sum(y == 0)}")
print(f"number of labels = 1: {np.sum(y == 1)}")
```

We now plot some data samples and their corresponding label (either $0$ (abnormal) or $1$ (normal)).
```{python}
import matplotlib.pyplot as plt
import numpy as np
# Plot some of the data for better understanding
nrows, ncols = 2, 3     # 2 rows, 3 columns for 6 subplots
plt.figure(figsize=(6, 4))
np.random.seed(seed=42)         # just for reproducibility purpose

for i in range(nrows * ncols):
    plt.subplot(nrows, ncols, i+1)
    idx = np.random.randint(low=0, high=X.shape[0])
    plt.plot(data[idx])
    text = "normal" if y[idx] == 1 else "abnormal"
    plt.title(f"label = {int(y[idx])}: {text}")
    plt.xticks(np.linspace(0, 120, 5))
    plt.grid(True)
    
plt.tight_layout()
```

Next, we split the original dataset into two sets: training set and test set. We can use any splitting proportion we want. Here, we split $80\% - 20\%$ as above.
```{python}
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)
n_samples_train, n_samples_test, n_samples = X_train.shape[0], X_test.shape[0], X.shape[0]
ratio = (n_samples_train/n_samples, n_samples_test/n_samples)

print(f"Number of samples in training set: {n_samples_train}")
print(f"Number of samples in test set: {n_samples_test}")
print(f"Split ratio = {ratio[0]:.4f}, {ratio[1]:.4f}")
```

Now, we define a `LogisticRegression` model object and perform the training
```{python}
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)
```

Unlike regression problems in which we can measure how well the model is by using $R^2$ score, we cannot use this score to measure how well the model performs on classification problem. Instead, we use the `accuracy_score` to measure how accurate the model can classify the samples into the right category. In our case, we measure how well the model can predict the samples in the test set. The score is just simply the number of correct predictions divided by the total number of predictions made.

```{python}
from sklearn.metrics import accuracy_score
y_pred = log_reg.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Model accuracy: {accuracy: .4f}")
```

The model can make prediction fantastically, almost $99\%$ correctly. Now, we plot some data in the test set and show both the prediction as well as the ground truth label (the labels that are given by the data).
```{python}
nrows, ncols = 2, 3
plt.figure(figsize=(6, 4))
np.random.seed(seed=42)         # just for reproducibility purpose
for i in range(nrows * ncols):
    plt.subplot(nrows, ncols, i+1)
    
    idx = np.random.randint(low=0, high=X_test.shape[0])
    actual_label = int(y_test[idx])
    # convert this to a row vector which is a (1 x n) matrix.
    data_point = X_test[idx].reshape(1, -1)     
    predicted_label = int(log_reg.predict(data_point)[0])

    plt.plot(X_test[idx])
    plt.title(f"Actual: {actual_label} | Pred: {predicted_label}")
    plt.xticks(np.linspace(0, 120, 5))
    plt.grid(True)
    
plt.tight_layout()
```